site_name: Walker_V's Notebook
site_url: https://VictorWang712.github.io/Note/
site_author: Walker_V
site_description: Walker_V's Notebook
repo_url: https://github.com/VictorWang712/Note/
repo_name: VictorWang712/Note
copyright: Copyright &copy; 2025 Walker_V

theme:
  name: material
  custom_dir: overrides
  language: en
  font: 
    text: LXGW WenKai Screen
    code: CodeNewRoman Nerd Font Mono
  icon:
    logo: material/book-outline
  favicon: assets/images/icons/favicon.png

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: custom/day-and-night
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: octicons/sun-16
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: octicons/moon-16

  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.code.select

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VictorWang712/
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/59307750/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<victorwang712@zju.edu.cn>

extra_css:
  - stylesheets/css/card.css
  - stylesheets/css/flink.css
  - stylesheets/css/rounded_corner.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - statistics:
      page_images: false
      page_check_metadata: comments

nav:
  - Home: 
    - index.md
    - friends_links.md
  - Mathematics:
    - mathematics/mathematical_analysis_I.md
    - mathematics/mathematical_analysis_II.md
    - 离散数学:
      - mathematics/discrete_mathematics/index.md
      - mathematics/discrete_mathematics/chapter_1.md
      - mathematics/discrete_mathematics/chapter_2.md
      - mathematics/discrete_mathematics/chapter_3.md
      - mathematics/discrete_mathematics/chapter_4.md
      - mathematics/discrete_mathematics/chapter_5.md
      - mathematics/discrete_mathematics/chapter_6.md
      - mathematics/discrete_mathematics/chapter_7.md
      - mathematics/discrete_mathematics/chapter_8.md
    - 概率论与数理统计:
      - mathematics/probability_and_statistics/index.md
      - mathematics/probability_and_statistics/chapter_1.md
      - mathematics/probability_and_statistics/chapter_2.md
      - mathematics/probability_and_statistics/chapter_3.md
      - mathematics/probability_and_statistics/chapter_4.md
      - mathematics/probability_and_statistics/chapter_5.md
      - mathematics/probability_and_statistics/chapter_6.md
  - Physics:
    - physics/general_physics_I.md
  - Chemistry:
    - chemistry/general_chemistry.md
  - Computer Science:
    - computer_science/programming_and_algorithm_basics.md
    - 数字逻辑设计:
      - computer_science/digital_logic_design/index.md
      - computer_science/digital_logic_design/chapter_1.md
      - computer_science/digital_logic_design/chapter_2.md
      - computer_science/digital_logic_design/chapter_3.md
      - computer_science/digital_logic_design/chapter_4.md
      - computer_science/digital_logic_design/chapter_5.md
      - computer_science/digital_logic_design/chapter_6.md
      - computer_science/digital_logic_design/chapter_7.md
    - 计算机组成:
      - computer_science/computer_organisation/index.md
      - computer_science/computer_organisation/chapter_1.md
      - computer_science/computer_organisation/chapter_2.md
      - computer_science/computer_organisation/chapter_3.md
      - computer_science/computer_organisation/chapter_4.md
    - 数据结构基础:
      - computer_science/data_structure_basics/index.md
      - computer_science/data_structure_basics/chapter_1.md
      - computer_science/data_structure_basics/chapter_2.md
      - computer_science/data_structure_basics/chapter_3.md
      - computer_science/data_structure_basics/chapter_4.md
      - computer_science/data_structure_basics/chapter_5.md
      - computer_science/data_structure_basics/chapter_6.md
      - computer_science/data_structure_basics/chapter_7.md
      - computer_science/data_structure_basics/chapter_8.md
      - computer_science/data_structure_basics/mistakes.md
    - 高级数据结构与算法分析:
      - computer_science/advanced_data_structure/index.md
      - computer_science/advanced_data_structure/chapter_1.md
      - computer_science/advanced_data_structure/chapter_2.md
      - computer_science/advanced_data_structure/chapter_3.md
      - computer_science/advanced_data_structure/chapter_4.md
      - computer_science/advanced_data_structure/chapter_5.md
      - computer_science/advanced_data_structure/chapter_6.md
      - computer_science/advanced_data_structure/chapter_7.md
      - computer_science/advanced_data_structure/mistakes.md
    - 静态程序分析*:
      - computer_science/static_program_analysis/index.md
      - computer_science/static_program_analysis/chapter_1.md
      - computer_science/static_program_analysis/chapter_2.md
    - 代理式人工智能*:
      - computer_science/agentic_ai/index.md
      - computer_science/agentic_ai/chapter_1.md
  - Science Research:
    - 论文阅读:
      - science_research/papers/arXiv_2306_13063.md
      - science_research/papers/arXiv_2405_12641.md
      - science_research/papers/arXiv_2404_19318.md
      - science_research/papers/arXiv_2306_00108.md
      - science_research/papers/arXiv_2402_02047.md
      - science_research/papers/arXiv_2403_16437.md
      - science_research/papers/arXiv_2404_14662.md
      - science_research/papers/arXiv_2503_04149.md
      - science_research/papers/arXiv_1511_06279.md
      - science_research/papers/arXiv_1611_01989.md
      - science_research/papers/arXiv_2504_01943.md
  - Others:
    - Oxford Prospects Programmes '25 Winter:
      - others/OPP/index.md
      - others/OPP/lecture_1.md
      - others/OPP/workshop_1.md
      - others/OPP/lecture_2.md
      - others/OPP/lecture_3.md
      - others/OPP/lecture_4.md
      - others/OPP/workshop_2.md
      - others/OPP/lecture_5.md
      - others/OPP/lecture_6.md
      - others/OPP/lecture_7.md
      - others/OPP/lecture_8.md
      - others/OPP/workshop_3.md
      - others/OPP/workshop_4.md
      - others/OPP/lecture_9.md
      - others/OPP/lecture_10.md
      - others/OPP/lecture_11.md
      - others/OPP/lecture_12.md
      - others/OPP/lecture_13.md
      - others/OPP/workshop_5.md
      - others/OPP/workshop_6.md
      - others/OPP/workshop_7.md
      - others/OPP/lecture_14.md
      - others/OPP/lecture_15.md
      - others/OPP/lecture_16.md
      - others/OPP/lecture_17.md
      - others/OPP/lecture_18.md
      - others/OPP/lecture_19.md
      - others/OPP/lecture_20.md
      - others/OPP/lecture_21.md
